CREATE TABLE "GameArea" ("id" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"discipline" "Discipline" NOT NULL,CONSTRAINT "GameArea_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Position" ("id" TEXT NOT NULL,"gameAreaId" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"context" "AssessmentContext" NOT NULL,CONSTRAINT "Position_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SkillGroup" ("id" TEXT NOT NULL,"positionId" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,CONSTRAINT "SkillGroup_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Technique" ("id" TEXT NOT NULL,"skillGroupId" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,CONSTRAINT "Technique_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TechniqueVariant" ("id" TEXT NOT NULL,"techniqueId" TEXT NOT NULL,"discipline" "Discipline" NOT NULL,"name" TEXT NOT NULL,CONSTRAINT "TechniqueVariant_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Movement" ("id" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,CONSTRAINT "Movement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Drill" ("id" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"techniqueId" TEXT,"movementId" TEXT,CONSTRAINT "Drill_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Flow" ("id" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"discipline" "Discipline" NOT NULL,"positionId" TEXT,CONSTRAINT "Flow_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Video" ("id" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"storageKey" TEXT NOT NULL,"published" BOOLEAN NOT NULL DEFAULT false,"durationSec" INTEGER,"positionId" TEXT,"techniqueId" TEXT,"variantId" TEXT,"movementId" TEXT,"drillId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Video_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "GameArea_key_key" ON "GameArea"("key");
CREATE UNIQUE INDEX "Position_gameAreaId_key_key" ON "Position"("gameAreaId","key");
CREATE UNIQUE INDEX "SkillGroup_positionId_key_key" ON "SkillGroup"("positionId","key");
CREATE UNIQUE INDEX "Technique_key_key" ON "Technique"("key");
CREATE UNIQUE INDEX "TechniqueVariant_techniqueId_discipline_key" ON "TechniqueVariant"("techniqueId","discipline");
CREATE UNIQUE INDEX "Movement_key_key" ON "Movement"("key");
CREATE UNIQUE INDEX "Drill_key_key" ON "Drill"("key");
CREATE UNIQUE INDEX "Flow_key_key" ON "Flow"("key");
ALTER TABLE "Position" ADD CONSTRAINT "Position_gameAreaId_fkey" FOREIGN KEY ("gameAreaId") REFERENCES "GameArea"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SkillGroup" ADD CONSTRAINT "SkillGroup_positionId_fkey" FOREIGN KEY ("positionId") REFERENCES "Position"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Technique" ADD CONSTRAINT "Technique_skillGroupId_fkey" FOREIGN KEY ("skillGroupId") REFERENCES "SkillGroup"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TechniqueVariant" ADD CONSTRAINT "TechniqueVariant_techniqueId_fkey" FOREIGN KEY ("techniqueId") REFERENCES "Technique"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Drill" ADD CONSTRAINT "Drill_techniqueId_fkey" FOREIGN KEY ("techniqueId") REFERENCES "Technique"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Drill" ADD CONSTRAINT "Drill_movementId_fkey" FOREIGN KEY ("movementId") REFERENCES "Movement"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Flow" ADD CONSTRAINT "Flow_positionId_fkey" FOREIGN KEY ("positionId") REFERENCES "Position"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Video" ADD CONSTRAINT "Video_positionId_fkey" FOREIGN KEY ("positionId") REFERENCES "Position"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Video" ADD CONSTRAINT "Video_techniqueId_fkey" FOREIGN KEY ("techniqueId") REFERENCES "Technique"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Video" ADD CONSTRAINT "Video_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "TechniqueVariant"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Video" ADD CONSTRAINT "Video_movementId_fkey" FOREIGN KEY ("movementId") REFERENCES "Movement"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Video" ADD CONSTRAINT "Video_drillId_fkey" FOREIGN KEY ("drillId") REFERENCES "Drill"("id") ON DELETE SET NULL ON UPDATE CASCADE;
